export const SET_ARENA_ACTIVE = "SET_ARENA_ACTIVE";
export const SET_ARENA_DATA = "SET_ARENA_DATA";

export const SET_PLAYER_PROPERTY = "SET_PLAYER_PROPERTY";
export const SET_PLAYER_ACCOUNT_ID = "SET_PLAYER_ACCOUNT_ID";
export const SET_PLAYER_HIDDEN = "SET_PLAYER_HIDDEN";
export const SET_PLAYER_DATA = "SET_PLAYER_DATA";
export const SET_PLAYER_STATS = "SET_PLAYER_STATS";
export const SET_CLAN_DATA = "SET_CLAN_DATA";
export const SET_SHIP_DATA = "SET_SHIP_DATA";
export const SET_SHIP_STATS = "SET_SHIP_STATS";

export const SET_PLAYER_LIST_SORT = "SET_PLAYER_LIST_SORT";

export const ADD_ERROR = "ADD_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_WOWS_API_KEY = "SET_WOWS_API_KEY";
export const SET_WOWS_API_URL = "SET_WOWS_API_URL";
export const SET_WOWS_PATH = "SET_WOWS_PATH";
export const SET_WOWS_MATCHGROUP = "SET_WOWS_MATCHGROUP";

// progress counter
export const SET_TOTAL_OPERATIONS = "SET_TOTAL_OPERATIONS";
export const INC_COMPLETED_OPERATIONS = "INC_COMPLETED_OPERATIONS";
