export const SET_ARENA_ACTIVE = 'SET_ARENA_ACTIVE'
export const SET_ARENA_DATA = 'SET_ARENA_DATA'
export const INITIALIZE_PLAYER_DATA = 'INITIALIZE_PLAYER_DATA'
export const SET_PLAYER_DATA = 'SET_PLAYER_DATA'
export const SET_PERSONAL_DATA = 'SET_PERSONAL_DATA'
export const SET_CLAN_DATA = 'SET_CLAN_DATA'
export const SET_SHIP_DATA = 'SET_SHIP_DATA'

export const SET_PLAYER_LIST_SORT = 'SET_PLAYER_LIST_SORT'

export const ADD_ERROR = 'ADD_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const SET_WOWS_API_KEY = 'SET_WOWS_API_KEY'
export const SET_WOWS_API_URL = 'SET_WOWS_API_URL'
export const SET_WOWS_PATH = 'SET_WOWS_PATH'
export const SET_WOWS_MATCHGROUP = 'SET_WOWS_MATCHGROUP'
