export const SET_ARENA_ACTIVE = 'SET_ARENA_ACTIVE'
export const SET_ARENA_DATA = 'SET_ARENA_DATA'
export const INITIALIZE_PLAYER_DATA = 'INITIALIZE_PLAYER_DATA'
export const SET_PLAYER_DATA = 'SET_PLAYER_DATA'

export const SET_PLAYER_LIST_SORT = 'SET_PLAYER_LIST_SORT'

export const SET_WOWS_API_KEY = 'SET_WOWS_API_KEY'
export const SET_WOWS_API_URL = 'SET_WOWS_API_URL'
export const SET_WOWS_PATH = 'SET_WOWS_PATH'
